name = "backend"
main = "src/index.ts"
compatibility_date = "2024-11-04"

compatibility_flags = ["nodejs_compat"]


vars = { DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZWYxZWYzMWEtNzA3ZC00MDc0LWE4NzQtNjU0ZGM0YjY0ODllIiwidGVuYW50X2lkIjoiNDEwZjNkNmQ5ZWJhNDI5YWJmZmU3ODM3NTk1NGUzOTYwODFmMDFlYjMzZmYxYzQ5ODY1OWYzNTk4YWMwMzI0MyIsImludGVybmFsX3NlY3JldCI6ImEzMjQ3MmVjLWViNDEtNGU2NS1hM2JlLTQ3MDA1NWFkOGY0OSJ9.d89iNo-FQCELbPlYzIlzTAwOOfXNi7LcW3NxAKT1ErU", JWT_SECRET = "roxy@rola", CLOUDINARY_CLOUD_NAME="Hoomies", CLOUDINARY_API_KEY="364537581171581", CLOUDINARY_API_SECRET="OyDovtA7TmeO59uRJOHNhKQQIP4" }

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1